### ISSUE TITLE
Reporting port 9060 already in use

### ISSUE THREAD

**Issue by tcreek** [negbie/heplify-xrcollector#1]
When trying to run the collector on the same system as heplify-server using the listed examples (shown below),  I am getting the following error:

>2019/01/02 14:14:12 listen udp 127.0.0.1:9060: bind: address already in use

I assume the switch "-hs" means heplify server I need to send the data to from the heplify-xrcollector, and "-xs" means the  port the this very heplify-xrcollector is would be using . Would that be correct?

Why would it need to grab the use of port 9060 if it needs to contact that port to send data to?

The Examples

> # Listen on 0.0.0.0:9064 for vq-rtcpxr and send it as HEP to 127.0.0.1:9060
> ./heplify-xrcollector
> 
> # Listen on 0.0.0.0:9066 for vq-rtcpxr and send it as HEP to 192.168.1.10:9060
> ./heplify-xrcollector -xs :9066 -hs 192.168.1.10:9060
> 
> # Additionally change HEP ID to 1234 and log with debug level
> ./heplify-xrcollector -xs :9066 -hs 192.168.1.10:9060 -hi 1234 -debug

**Comment by negbie** [comment]
Please post the output of ./heplify-xrcollector -h

I guess you aren't using the latest version 0.3

**Comment by tcreek** [comment]
Yes, you are correct. My bad. 

Thanks for responding so quickly.

**Comment by alexllobet** [comment]
Hi! I have the same problem! I'm using version 0.4 and Kamailio. I have got the same error: address already in use.
![image](https://user-images.githubusercontent.com/26059063/69268131-db61a700-0bce-11ea-9893-0791483ec5bb.png)

And if we command netstat:
![image](https://user-images.githubusercontent.com/26059063/69268238-0946eb80-0bcf-11ea-9cbf-0329ea451199.png)


I assume that the collector needs to listen the port in which the SIP traffic will go through...

**Comment by negbie** [comment]
Hi, just use another one. You can specify it with -xs flag.

**Comment by alexllobet** [comment]
Thanks for answering so fast! I thought about doing so but, as far as I can understand, the port we are listening into should receive SIP traffic so the collector can do its job, am I right? I'm receiving traffic on port 5060!

**Comment by negbie** [comment]
Yes Kamailio need to listen on port 5060 and then you cannot let the collector listen on the same port but for the collector it does not matter on which port it will listen. It does not receive SIP but RTCP XR Report from the phones directly. Maybe there are phones which do only send the reports to ip:5060 but it's not the fault of the collector. So you can change thecollector port and point your phones to the new collector IP.

**Comment by negbie** [comment]
If you do not understand what I've wrote, you should first try to understand what SIP RTCP-XR is. Check this out:

https://www.voip-info.org/rtcp-xr/

**Comment by alexllobet** [comment]
ok yes! I have just understood the whole thing! Thank you very much!

**Comment by negbie** [comment]
Cool. So I would try to set -xs to for example yourserverip:6000 and point your phones to that socket and see what happens.

**Comment by negbie** [comment]
For snom phones check out this:
http://wiki.snom.com/Settings/vq_report_collector
